//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cagem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAboutsMe
    {
        public int AboutsMeID { get; set; }
        public string NameSurname { get; set; }
        public string Description { get; set; }
    }
}
